apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quickinv.fullname" . }}-db
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | quote }}
